### ISSUE TITLE
[weird bed model]: 

### ISSUE THREAD

**Issue by AnomalousDeity** [terrarium-earth/Handcrafted#1]
### Bug Description

I am unsure if its a mod (yes it works on its own just not with my entire mod list) I am on my server and some players say it looks fine and others say it looks like 2 plank blocks
![2022-12-20_21 27 10](https://user-images.githubusercontent.com/91780401/208829327-78f45a07-3a0d-46ad-bca2-529cc825f7b4.png)

### Expected Behavior

fancy and comfy looking beds

### Version

2.0.1

### Mod Loader Version

1.19.2

### Mod Loader

Fabric

### Logs or additional context

I would love to put my log here cept pastebin says my log is too large and ive exceeded their limit. Its a lengthy log

**Comment by AnomalousDeity** [comment]
Found the mod culprit, its bugging out with better beds mod

**Comment by AlexNijjar** [comment]
weird, better beds should not be touching modded beds

**Comment by AnomalousDeity** [comment]
Yea it shouldnt yet when its removed the beds look awesome so i am unsure why its weirding out with it

**Comment by Aquaeyes** [comment]
For me, beds render correctly, but in item form they're 2 planks as shown above.

emi-0.5.3+1.19.2.jar
enhancedblockentities-0.7.2+1.19.2.jar
handcrafted-fabric-1.19.2-2.0.1.jar
qfapi-4.0.0-beta.24_qsl-3.0.0-beta.24_fapi-0.68.0_mc-1.19.2.jar
