### ISSUE TITLE
[Bug]: Sleeping on handcrafted beds resets day counter

### ISSUE THREAD

**Issue by BosuThau** [terrarium-earth/Handcrafted#104]
### Bug Description

I have a survival server, and sleeping in handcrafted beds resets day counter to 0.

### Version

4.0.1

### Mod Loader Version

1.21

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by TechnoSparks** [comment]
Because you closed the issue, may I know how you resolve this issue?

**Comment by BosuThau** [comment]
> Because you closed the issue, may I know how you resolve this issue?

Another mod which interacts with sleeping was causing this issue, not the beds from this mod. My initial presumption was that the custom beds interacted how sleep was done, but the mod Sleep was resetting the day count. I totally forgot I put that mod in first place.

**Comment by TechnoSparks** [comment]
I don't have "Sleep" mod installed but I experience random day counter reset. Kinda hard for me to pin down on the exact mod is doing it though. It happens randomly and not once
