### ISSUE TITLE
[Feature Request]: Why not 1.18.2 but 1.18.1?

### ISSUE THREAD

**Issue by Timanfour** [terrarium-earth/Handcrafted#110]
### Is your feature request related to a problem?

I dont know if im dumb or smth but there isnt a 1.18.2 version but a 1.18.1 version?

### Mod Version

1.0.0

### Mod Loader Version

1.20.1

### Mod Loader

Forge

**Comment by Timanfour** [comment]
Hell nah, 350 dollars

**Comment by AlexNijjar** [comment]
the 1.18.1 version was a completely different mod. it just had one set of fantasy furniture. the mod was remade in 1.19.2 and wont be backported. also what?
