### ISSUE TITLE
[Bug]: Desk displays the wrong tooltip

### ISSUE THREAD

**Issue by vinnyg0621** [terrarium-earth/Handcrafted#112]
### Bug Description

![Screenshot 2024-07-29 215540](https://github.com/user-attachments/assets/14760789-cd39-444b-bdf1-7666400407f1)

### How to Reproduce?

1. Hover over the spruce desk
2. hold Shift

### Expected Behavior

I expected the information to make more sense, but this desk **changes the look of blocks**? what the heck...?

### Version

3.0.6

### Mod Loader Version

1.20.1 - 47.3.5

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
I believe that's the tooltip for the hammer; I must have used the wrong one for the desk. It should say that you can place sheets on it

**Comment by vinnyg0621** [comment]
oh ok, thank you.
