### ISSUE TITLE
[Bug]: Handcrafted paintings spawn in Twilight Forest structures.

### ISSUE THREAD

**Issue by Aquaeyes** [terrarium-earth/Handcrafted#12]
### Bug Description

Twilight Forest attempts to use textures for Handcrafted paintings on an entity which is not UV mapped to deal with those textures. This is apparently an issue with Handcrafted according to the Twilight Forest devs.

### How to Reproduce?

1. Have Twilight Forest installed alongside.
2. Go to Lich tower.
3. See that Twilight Forest is pulling from Handcrafted's paintings which have their own entity
type, and are incompatible with the default painting type.

### Expected Behavior

Only have Twilight Forest spawn Vanilla (and Ad Astra, also installed and works perfectly) paintings.
![](https://user-images.githubusercontent.com/10935410/209364961-e3f62d18-4e63-4dd0-bf22-f6eb7007d677.png)

### Version

2.0.1

### Mod Loader Version

1.19.2

### Mod Loader

Quilt

### Logs or additional context

https://github.com/TeamTwilight/twilightforest-fabric/issues/148#issuecomment-1426922584

**Comment by AlexNijjar** [comment]
I’ll add it as a tag instead of adding it to the painting registry. that should fix it
