### ISSUE TITLE
Problem with craftings[Bug]: 

### ISSUE THREAD

**Issue by Gislikol** [terrarium-earth/Handcrafted#13]
### Bug Description

ive been trying to craft some stuff and i need warped board to do it. which im suposed to get by putting warped planks in a stonecutter. but when i do it there is no options at all. like i put the plank and there is nothing. im i doing something wrong? please help. i really wanna use those buildings.

### Version

2.0.2

### Mod Loader Version

1.19.2

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
you throw them on the stonecutter
