### ISSUE TITLE
Nothing to see here

### ISSUE THREAD

**Issue by WillianBK** [terrarium-earth/Handcrafted#18]
### Bug Description

Glass and Glasspanes recipes not working on botanist workbench!

### How to Reproduce?

Open botanist workbench
Put glass panes on the desired slot
Nothing happens

### Expected Behavior

Absolute no recipes to use, even it showing on REI

### Version

2.0.2

### Mod Loader Version

1.19.2 latest fabric version

### Mod Loader

Fabric

**Comment by CodexAdrian** [comment]
Now i could be wrong, but this kinda sounds like Chipped

**Comment by AlexNijjar** [comment]
LMAO
