### ISSUE TITLE
[Bug]: beds dont look correct in inventory

### ISSUE THREAD

**Issue by BeyondTheStarss** [terrarium-earth/Handcrafted#20]
### Bug Description

Beds in the inventory appear as 2 planks (respective type) next to eachother but when placed down the bed is fine

### Expected Behavior

beds to have a normal appearance in the menu

### Version

2.0.6

### Mod Loader Version

1.19.2 - 1.14.14

### Mod Loader

Fabric

### Logs or additional context

![image](https://user-images.githubusercontent.com/102612648/225570938-c2cd0890-6634-4c0a-81b5-e8768c7b4bd4.png)

**Comment by AngleNaris** [comment]
it's still have render issues. 
latest 2.0.6 + minecraft 1.19.2
bed is normally in menu but appeared as 2 planks when placed on ground.

**Comment by TheGamerCanine** [comment]
I have the same issue
