### ISSUE TITLE
[Bug]: Targeting and breaking the top half of a skeleton trophy drops its item in creative, but not the bottom half

### ISSUE THREAD

**Issue by marinom1** [terrarium-earth/Handcrafted#21]
### Bug Description

When the player is playing in a creative world on ATM8 and breaks a skeleton trophy by targeting the upper half of the block, the item drops.

AlltheMods8 1.0.13
Handcrafted 2.0.2

### How to Reproduce?

-Load up a creative world of ATM8 modpack
- Retrieve a skeleton trophy to your hotbar
- Place it down in the world
- Aim your target crosshairs on the top half of the skeleton trophy
- Break the block
- The item drops

### Expected Behavior

The item should not drop in creative mode.

### Version

2.0.2

### Mod Loader Version

1.19.2 - AlltheMods8 1.0.13

### Mod Loader

Forge

### Logs or additional context

https://user-images.githubusercontent.com/20889773/226063940-c7b4a7fa-4767-4744-af15-dcbcd939e32b.mp4

**Comment by AlexNijjar** [comment]
Fixed in 563b0c1
