### ISSUE TITLE
[Feature Request]: Make colored beds craftable

### ISSUE THREAD

**Issue by ereese99** [terrarium-earth/Handcrafted#22]
### Is your feature request related to a problem?

Yes, the shift+click of the sheets / cushions is not working. Nothing happens in the latest version ( I suspect Sleep Tight mod incompat)

### Solution(s)

Make colored beds craftable. Every color. Not necessarily every color COMBO though.

### Describe alternatives you've considered

Idk, it just doesnt work for me with the way it's setup

### Mod Version

2.0.6

### Mod Loader Version

1.19.2 - 0.14.17

### Mod Loader

Fabric

**Comment by AlexNijjar** [comment]
I spoke with the sleep tight dev and they said they will fix it. I think having 16 beds makes it too cluttered.

**Comment by AlexNijjar** [comment]
As it's their issue, will close
