### ISSUE TITLE
[Feature Request]: Config for board cutting

### ISSUE THREAD

**Issue by ChloeDawn** [terrarium-earth/Handcrafted#23]
### Is your feature request related to a problem?

Currently, there is no way to disable the stone cutter board cutting mechanic.

### Solution(s)

Implement a config flag to toggle the mechanic.

### Describe alternatives you've considered

Implement a data-pack-overridable recipe as per the TODO comment in the class.

### Mod Version

forge-1.19.4-2.2.0

### Mod Loader Version

1.19.2 - 43.2.7

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
yeah we're going to make it a recipe

**Comment by AlexNijjar** [comment]
Boards are getting removed
