### ISSUE TITLE
[Bug]: Books are invisible ?

### ISSUE THREAD

**Issue by Yugniam** [terrarium-earth/Handcrafted#25]
### Bug Description

I have a wierd bug were the stackable books are invisible, i can still see the hitbox, have colision to it but it seems invisible.
![2023-04-04_16 14 56](https://user-images.githubusercontent.com/129871456/229821000-efc6fb93-2434-4e12-aedb-b8f21b645985.png)

### How to Reproduce?

Place the stackable book on the ground

### Expected Behavior

to show the books placed on the ground

### Version

2.2.0

### Mod Loader Version

1.19.4

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
can you try without sodium?

**Comment by Yugniam** [comment]
![2023-04-05_01 11 28](https://user-images.githubusercontent.com/129871456/229942360-a8815598-d9bc-45ef-af04-59f038836e56.png)
same problem without sodium, that is kinda wierd ngl

**Comment by MadameElfarran** [comment]
I don't know if this warrants a separate issue but I encountered the same bug with the **Physics mod** installed alongside Handcrafted on both Quilt & Fabric Loaders on 1.19.4

**Comment by Yugniam** [comment]
Wow, actually the case, thank you !
It is the combination with thoses two mods that makes the books invisible what's funny is that it's only the books !
The rest of the furnitures are working perfectly well..
Thanks u so much !

**Comment by MrKashew** [comment]
any chance this fix can be backported to Forge 1.19.4 version - encountering same issue in modpack 😢
