### ISSUE TITLE
[Bug]: Counters don't open like chests

### ISSUE THREAD

**Issue by IsWinth** [terrarium-earth/Handcrafted#26]
### Bug Description

Counters are crafted from boards and a chest, but after placing a block in the world, they do not open with the right mouse button.

### How to Reproduce?

1. Retrieve a counter made of any wood into your hotbar
2. Place it down in the world
3. Right-click on the counter block

### Expected Behavior

The counter should open like a chest

### Version

2.0.6

### Mod Loader Version

1.19.2 - 43.2.4

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by Badvilll** [comment]
Is there any updates on this?

**Comment by AlexNijjar** [comment]
it’s been fixed and will be in the next update
