### ISSUE TITLE
[Feature Request]: Every Compat

### ISSUE THREAD

**Issue by legoatoom** [terrarium-earth/Handcrafted#27]
### Is your feature request related to a problem?

When using different mods, such as "Oh The Biomes You'll Go" that add new wood types, this mod does not add the furniture for those wood types.

### Solution(s)

When using [Every Compat](https://modrinth.com/mod/every-compat), you can support the creation of all types of wood for the furniture. As far as I understood, this mod has API that makes it easy to generate new furniture with generated textures as well. 

### Mod Version

2.0.6

### Mod Loader Version

1.19.2 - 0.14.19

### Mod Loader

Fabric

**Comment by AlexNijjar** [comment]
I'm a little bit hesitant to support something like this. Handcrafted furniture is quite expensive, in terms of blockstates. Support for all these different wood types may add tens of thousands of additional blockstates, thus would increase the loadtime significantly.
