### ISSUE TITLE
Beds on forge dont skip nights

### ISSUE THREAD

**Issue by Thepigcat76** [terrarium-earth/Handcrafted#3]
### Bug Description

Handcrafted beds at least in the forge version dont skip nights!

### Version

handcrafted-forge-1.19.2-2.0.1

### Mod Loader Version

1.19.2

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
they seem to be skipping nights for me. Make sure the gamerule "doDaylightCycle" is set to true. If it's still happening, maybe some other mod is breaking it?

**Comment by AlexNijjar** [comment]
if it's still broken lmk
