### ISSUE TITLE
[Feature Request]: make cats sleep in beds!

### ISSUE THREAD

**Issue by kad0mad0** [terrarium-earth/Handcrafted#30]
### Is your feature request related to a problem?

its very frustrating to have to use vanilla beds so cats sleep with me :(
i installed the mod for the nice beds! but it removes my favorite feature...

### Solution(s)

cats should be able to sleep on beds like on vanilla beds!

### Mod Version

2.2.0

### Mod Loader Version

0.14.19

### Mod Loader

Fabric

**Comment by AlexNijjar** [comment]
<img width="1512" alt="Screenshot 2023-10-09 at 1 48 19 AM" src="https://github.com/terrarium-earth/Handcrafted/assets/61668546/766f2ca1-08f0-4ac8-9987-811f3bdec729">

Will be in the next update!
