### ISSUE TITLE
[Bug]: Incompatibility with Better Beds

### ISSUE THREAD

**Issue by PanoptesDreams** [terrarium-earth/Handcrafted#31]
### Bug Description

Having Handcrafted and Better Beds installed together messes up bed models.
Searching through the closed issues is what tipped me off. #1 

Please add an incompatible flag to your manifest to prevent users from using the mods together.
Oh and all the other metadata you're missing too. You're asking for a version number but it doesn't display in Prism.

I will be asking Better Beds to handle it on their end too.

### How to Reproduce?

Have Handcrafted and Better Beds installed together.

### Version

2.2.0

### Mod Loader Version

1.19.4 - 0.14.19

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
should be fixed in 563b0c1
