### ISSUE TITLE
[Feature Request]: 1.16.5 forge

### ISSUE THREAD

**Issue by ALEILGOD** [terrarium-earth/Handcrafted#32]
### Is your feature request related to a problem?

hi, im making a private modpack and i want this mod for 1.16.5 with the modloader forge

### Solution(s)

so can you make this mod for 1.16.5 forge or you can't?
if you can, could you port the mod in 1.16.5 for the modloader forge
**Thanks for reading**

### Describe alternatives you've considered

maybe you could use another library for the mod or make it completely standalone

### Mod Version

no one

### Mod Loader Version

no one

### Mod Loader

forge

**Comment by AlexNijjar** [comment]
We are currently not doing any backports. Sorry.
