### ISSUE TITLE
[Bug]: cherry and bamboo planks  don't turn into  boards when landing on stonecutter

### ISSUE THREAD

**Issue by xXLightdustXx** [terrarium-earth/Handcrafted#36]
### Bug Description

As i was playing literally an hour ago i was getting the ingredients done to make myself a fancy bed i through cherry planks on the stonecutter and they wouldn't turn into cherry boards.
Yet for the other planks that i had it would turn them into boards
Then rn as I'm typing this i made a new creative world (to see if it was maybe due to my world that was having an issue with not making boards) and found the same issue with bamboo planks.

### How to Reproduce?

1 Through either cherry or bamboo planks in the stone cutter and they don't turn into boards 

### Expected Behavior

I was expecting to have boards yet here we are.

### Version

1.20

### Mod Loader Version

1.20-2.3.1

### Mod Loader

Forge

### Logs or additional context

Im not 100% sure if the bug is bcs of the mod or maybe bcs of other mods. 
I have 14 other mods dowloaded with handcrafted

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
what version of the mod are you using?

this was fixed in 2.3.2
https://modrinth.com/mod/handcrafted/version/2.3.2
https://modrinth.com/mod/handcrafted/version/M0X2ttRF

**Comment by xXLightdustXx** [comment]
2.3.1

**Comment by xXLightdustXx** [comment]
*sigh* guess ill have to wait for these other mods that i have to get to 1.20.1

**Comment by xXLightdustXx** [comment]
Mb sorry for bothering

**Comment by AlexNijjar** [comment]
all 1.20 mods should be compatible with 1.20.1
