### ISSUE TITLE
[Feature Request]: Fill bowls with liquids

### ISSUE THREAD

**Issue by Aspurgus** [terrarium-earth/Handcrafted#37]
### Is your feature request related to a problem?

Bowls cant really hold anything

### Solution(s)

Using a bottle on a bowl will fill it with that fluid, and to add compatability with other mods, something like Supplementary's data driven jar fluids could be used. Water buckets could still waterlog bowls.

### Mod Version

2.0.6

### Mod Loader Version

1.19.2 - 43.2.8

### Mod Loader

Forge

**Comment by Aspurgus** [comment]
Adding on to this since I just realized, this could also apply to standalone cups and plates, and it's really odd that plates can only hold food when they're paired with a cup

**Comment by redwizard2022** [comment]
I agree it is a little weird not being able to do much with the cups, bowels etc. It would be really cool if you could put soups in the bowels too.

**Comment by ThatGravyBoat** [comment]
No, the bowls and cups are decorative :)
