### ISSUE TITLE
[Bug]: Crockery Combo destroys item on it when broken

### ISSUE THREAD

**Issue by taucxti** [terrarium-earth/Handcrafted#39]
### Bug Description

Accidentally placed my sword on a Yellow Crockery Combo and couldn't figure out how to get it back, tried mining the combo and lost my enchanted sword. It just drops the item, not the sword I placed on it.

### How to Reproduce?

1. Place Yellow Crockery Combo
2. Place item on top of it
3. Mine
4. Yellow Crockery Combo drops and can be looted, item does not and is despawned

### Expected Behavior

I expected to receive my item back. The item places upon it like an item frame, so I thought it would work the same way (left click removes the item, mining it drops both the item and the frame/crockery).

### Version

2.0.6

### Mod Loader Version

1.19.2 - 0.14.19

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by FellowEsin** [comment]
I'm playing the 2.0.6 version of the mod on Forge. You can't get the item at all. Not by left-clicking or breaking the crockery. So, I have the same problem.

**Comment by AlexNijjar** [comment]
fixed in 563b0c1

**Comment by FellowEsin** [comment]
Thank you soooooo much! Will update the mod :D Keep up the good work, and take care of yourself!

**Comment by AlexNijjar** [comment]
thanks, will be released in a few days. just going through testing right now.

**Comment by FellowEsin** [comment]
Yw! Will it be released for 1.20.1? I'm updating my instance to that version, that's why I asked

**Comment by AlexNijjar** [comment]
yep!

**Comment by FellowEsin** [comment]
Epic! Take your time, and thanks again!
