### ISSUE TITLE
Items disappear on the screen

### ISSUE THREAD

**Issue by VerWave** [terrarium-earth/Handcrafted#4]
### Bug Description

Hello. I have a small problem. If you take the screen away from some blocks, they disappear. Maybe this is normal, but not a single thing in other mods behaves this way. In the video, I showed how it looks (on vanilla minecraft)

https://user-images.githubusercontent.com/121665403/210053564-71b58624-3853-40c4-aaaa-0bf0738d1db5.mp4

### Version

handcrafted-forge-1.19.2-2.0.1

### Mod Loader Version

1.19.2

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
fixed in 2.0.2 for the statue and the bed. Didn't realize it happens with the bench as well
