### ISSUE TITLE
[Bug]: Players unable to interact with world after sitting in chairs or couch 

### ISSUE THREAD

**Issue by Secondbreakfastpip** [terrarium-earth/Handcrafted#40]
### Bug Description

after sitting in a chair from Handcrafted, players are unable to interact with the game world e.g. break blocks, die or receive harm, build. On the players screen they have exited the chair and walked away, however they show as still sitting in the chair to other players. Only way to fix this is to /kill the player in console.

### How to Reproduce?

1. place a chair or couch of any wood type
2. sit in the chair
3. leave the chair
4. attempt to break or place a block
[logs.zip](https://github.com/terrarium-earth/Handcrafted/files/11896418/logs.zip)

### Expected Behavior

players should be able to interact with the world after leaving the chair.

### Version

1.20.1

### Mod Loader Version

47.0.19

### Logs or additional context

https://pastebin.com/u0APyrQH

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
Cant reproduce
