### ISSUE TITLE
[Feature Request]: Make villagers able to sleep in fancy beds

### ISSUE THREAD

**Issue by somekindofanimal** [terrarium-earth/Handcrafted#45]
### Is your feature request related to a problem?

The feature is related to the fact that the fancy beds in Handcrafted are not assigned as villager points of interest, meaning that villagers cannot sleep in them.

### Solution(s)

Villagers should be able to sleep in fancy beds from Handcrafted.

### Describe alternatives you've considered

My current alternative is just not using the fancy beds because I need villagers to be able to sleep in them as well.  (Allowing villagers to sleep in them would also add additional compatibility with mods such as Sleep Tight that have features relating to beds being seen as villager points of interest.)

### Mod Version

2.0.6

### Mod Loader Version

1.19.2-2.0.6

### Mod Loader

Fabric

**Comment by AlexNijjar** [comment]
<img width="1512" alt="Screenshot 2023-10-09 at 1 50 28 AM" src="https://github.com/terrarium-earth/Handcrafted/assets/61668546/98b8926a-3521-46b3-b9b5-87de61c4a7cb">
Fixed in the next update
