### ISSUE TITLE
[Feature Request]: How do I get these furniture in Survival mode?

### ISSUE THREAD

**Issue by yunxiao1237** [terrarium-earth/Handcrafted#46]
### Is your feature request related to a problem?

I know the recipe for furniture. Most furniture requires planks to be composited, but I don't know how to get it, it can't be obtained by a stone cutter, and it can't go through a workbench.

### Mod Version

1.19.4

### Mod Loader Version

1

**Comment by AlexNijjar** [comment]
you throw the physical item on top of the stonecutter

**Comment by yunxiao1237** [comment]
thank you!
