### ISSUE TITLE
[Bug]: Server crashing on startup

### ISSUE THREAD

**Issue by jouki** [terrarium-earth/Handcrafted#48]
### Bug Description

Hello,
when I'm trying to start up the server with the mod it unfortunately crashes. If anything else is required let me know.

Cheers,
Jouki

### Version

2.3.2

### Mod Loader Version

47.1.0

### Mod Loader

Forge

### Logs or additional context

crash log:
https://gist.github.com/jouki/8368dfa1344c91aa409494157af4f104

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
Update Resourceful Lib
