### ISSUE TITLE
[Feature Request]: Remove wooden boards

### ISSUE THREAD

**Issue by MarioSMB** [terrarium-earth/Handcrafted#49]
### Is your feature request related to a problem?

As a first impression I believe the wooden boards mechanic overcomplicates crafting too much - sometimes less is more! In that vein, I'd like to suggest simply removing the wooden boards and using regular planks for the furniture crafting recipes.

### Solution(s)

Some recipes would make a lot more sense this way, for example: chiseled bookshelf uses 6 planks with a row of slabs in the middle, simply removing the slabs to keep the planks would make a shelf, etc. Not to mention the texture of the final item tends to look more like planks than the boards anyway!

### Describe alternatives you've considered

I understand that removing things isn't always a desired solution, but this is really a case I think would benefit everyone all around - even modders who may want to add their wood types for the furniture, one less custom item to make!

### Mod Version

2.3.2

### Mod Loader Version

1.20.1 - 47.1.43

### Mod Loader

Forge

**Comment by MarioSMB** [comment]
Additionally, in some cases, it would make more sense to use sticks over planks/boards, for example the hammer which clearly has a stick in the final item:  
![2023-07-28_21 02 56](https://github.com/terrarium-earth/Handcrafted/assets/1998392/fa47956f-465a-4997-a4e0-7b5e10c22616)

**Comment by AlexNijjar** [comment]
probably in a future update. Don't really like them

**Comment by AlexNijjar** [comment]
done in 563b0c1
