### ISSUE TITLE
[Bug]: Recipe Overlap

### ISSUE THREAD

**Issue by meatcereal** [terrarium-earth/Handcrafted#5]
### Bug Description

Dining Benches and tables have the same recipe.

### How to Reproduce?

1. Attempt to craft spruce table
2. Craft Dining bench instead

### Expected Behavior

2 Different recipes

### Version

2.0.1

### Mod Loader Version

1.19.2

### Mod Loader

Fabric

**Comment by AlexNijjar** [comment]
It's been fixed in the latest version https://www.curseforge.com/minecraft/mc-mods/handcrafted/files/4282207
