### ISSUE TITLE
[Bug]: Reasonably certain the Create integration recipes for Boards are, as is, not intended.

### ISSUE THREAD

**Issue by Inpaladin** [terrarium-earth/Handcrafted#51]
### Bug Description

The Create Mechanical Saw recipe automatically added by this mod for the various board types seems very incorrect.  
Currently: 
- Dark Oak, Mangrove, Oak, Spruce, and Warped Boards have a _**10%**_ chance to craft 4 from their respective planks
- Jungle Boards have a 25% chance to craft 3 from Jungle Planks
- Acacia and Birch Boards have a 25% chance to craft 2 from their respective planks
- Crimson Boards have a 10% chance to craft 2 from Crimson Planks

As you can see, not only are all of these chances very low, but both the chances and output are just not the same across wood types.

### How to Reproduce?

1. Install Create, Handcrafted, and JEI
2. check board recipes using JEI

You can also view the problem in the recipe JSONS, where it is also revealed that Acacia and Crimson Boards additionally have their "processingTime" set to "10", for some reason.

### Expected Behavior

I'd expect the recipes to just be the same as they are on the stonecutter, or at least have the same output/chance values across wood types.

### Version

2.0.6 for 1.19.2 but you can see the recipes are the same for the 1.20 version on the github

### Mod Loader Version

_

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [x] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Fixed in 3.0.1

**Comment by Inpaladin** [comment]
> Fixed in 3.0.1

Great to hear!
