### ISSUE TITLE
[Bug]: Fancy Bed are buggy

### ISSUE THREAD

**Issue by xTheKingCat** [terrarium-earth/Handcrafted#53]
### Bug Description

 Fancy bed icons are buggy in inventory, 2 woods appear of any type

### Version

2.0.6

### Mod Loader Version

1.19.2

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by Brcyden** [comment]
I have this issue too

**Comment by AlexNijjar** [comment]
fixed in 563b0c1
