### ISSUE TITLE
[Bug]: Incorrect lighting when using shaders (Iris)

### ISSUE THREAD

**Issue by vnsrz** [terrarium-earth/Handcrafted#55]
### Bug Description

When using shaders, blocks added by the mod don't get illuminated correctly, as if smooth lighting was turned off, giving a jagged appearance: 
![2023-08-16_08 43 38](https://github.com/terrarium-earth/Handcrafted/assets/78430207/cecbcc39-3089-4b86-b15a-c88db15e5a9c)
Lighting on regular blocks:
![2023-08-16_08 44 22](https://github.com/terrarium-earth/Handcrafted/assets/78430207/e485f1ea-1082-479c-848f-f6b09c6964ab)
This does not occur on dynamic lights, e.g., when the player is holding a light source.
![2023-08-16_08 41 42](https://github.com/terrarium-earth/Handcrafted/assets/78430207/3208fa68-6097-47c1-8f0a-c617d30b5612)
![2023-08-16_08 41 56](https://github.com/terrarium-earth/Handcrafted/assets/78430207/88829e9a-88be-4724-8775-4e76602c7358)

Also, the food items on the plates glow.

### How to Reproduce?

1. Place a cluster of blocks from the mod while shaders are active
2. Put a light source close to some of them
3. See error

### Expected Behavior

Blocks should have smooth lighting, and food on plates shouldn't glow.

### Version

3.0.1

### Mod Loader Version

0.14.22

### Mod Loader

Fabric

### Logs or additional context

Tested with Complementary Reimagined r2.2.1 and BSL v8.2.04.
With Vanilla Tweaks resource pack and without.
Iris version 1.6.7

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
should be fixed in 563b0c1
