### ISSUE TITLE
[Bug]: Physics Mod Compatibility Request | Invisible books 95.4% of the time.. 

### ISSUE THREAD

**Issue by Duxtorm** [terrarium-earth/Handcrafted#56]
### Bug Description

With the physics mod installed, most books seem to be invisible..

When I place a book down on a random spot, there's roughly a **95.4%** chance it will be invisible.. 
and every book in that same column of blocks from **-64 to 320** will be invisible, but there's roughly a **4.6%** chance that if I place a book in a random spot, the bottom book in the stack will be visible.. 
and every bottom book in any stack within that specific **-64 - 320** column will be visible.. but only the bottom book, the rest of the books in the stack remain invisible.

The following screenshots I've attached depict:

A 32 x 32 area that I've /filled with books, displaying the **4.6** visible and **95.4** invisible books; this area is set within a 2 x 2 chunk grid.

My cursor highlighting an invisible book.

A stack of books with the bottom book visible.

And a stack of book-stacks in the same column that are all bottom-book-visible.

![Screenshot 2023-08-20 232523](https://github.com/terrarium-earth/Handcrafted/assets/21279166/bf8c4c05-621f-4e46-b916-1c960a492b3d)
![Screenshot 2023-08-20 232818](https://github.com/terrarium-earth/Handcrafted/assets/21279166/dd4f4ae7-4bac-4d45-a5f7-994b1b38c5ac)
![Screenshot 2023-08-20 232859](https://github.com/terrarium-earth/Handcrafted/assets/21279166/01866c80-be58-4642-b6ac-925483314574)
![image](https://github.com/terrarium-earth/Handcrafted/assets/21279166/95a4fb16-597b-4924-8d85-946cee69ea85)

### How to Reproduce?

Run this mod alongside the physics mod.

### Expected Behavior

Visible books :D

### Version

3.0.1

### Mod Loader Version

1.20.1 - 47.1.30

### Mod Loader

Forge

### Logs or additional context

Log: https://pastebin.com/3iwkZGpC

### Code of Conduct

- [ ] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
should be fixed in 563b0c1
