### ISSUE TITLE
[Feature Request]: Make wooden boards fuel

### ISSUE THREAD

**Issue by ghost** [terrarium-earth/Handcrafted#58]
### Is your feature request related to a problem?

They would be 1/4 of the fuel of wooden planks, of course. I would like this feature for consistency's sake!!

### Mod Version

Latest (3.0.1)

### Mod Loader Version

1.20.1

### Mod Loader

Fabric

### Additional context

Making a modpack where wood directly crafts into boards, then into planks.

**Comment by AlexNijjar** [comment]
boards are getting removed 563b0c1
