### ISSUE TITLE
[Bug]: Fancy Painting Variants Missing Localization

### ISSUE THREAD

**Issue by ChloeDawn** [terrarium-earth/Handcrafted#60]
### Bug Description

Painting variants have lesser-known associated title and author translation keys, that are used in an item tooltip when said item contains an entity tag for the painting variant, e.g. `{EntityTag:{variant:"minecraft:kebab"}}`. When this tag is present, the translated strings are rendered, but due to the missing localization in Handcrafted, Fancy Painting's configured this way just show the raw translation keys. The format of the keys is as follows, and can also be seen applied in `HangingEntityItem#appendHoverText`:
```json
"painting.namespace.path.title"
"painting.namespace.path.author"
```

I encountered this when configuring EMI to show Fancy Painting variants in the same fashion that it shows Painting variants.
This will also be reproduceable in Jade once the [improved painting tooltips](https://github.com/Snownee/Jade/pull/300) are pushed to production.

![In-game screenshot of unlocalized tooltip](https://github.com/terrarium-earth/Handcrafted/assets/9869940/98f1b957-c028-42c4-ac51-520e803012cb)

### How to Reproduce?

1. Obtain a fancy painting item with an entity tag containing a variant.
2. The item tooltip will render raw translation keys.

### Expected Behavior

The item tooltip to render a localized title and author.

### Version

3.0.1

### Mod Loader Version

1.20.1 - 0.20.2

### Mod Loader

Quilt

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ChloeDawn** [comment]
I have generated basic localization for them using a snake case to title case conversion, however it may be a good idea to adjust some to have more natural/unique names. The generated author attributes are all "Handcrafted" as I do not know who to credit for each.

<details>
<summary><code>handcrafted/lang/en_us.json</code></summary>

```json
{
  "painting.handcrafted.pride_steve.title": "Pride Steve",
  "painting.handcrafted.pride_steve.author": "Handcrafted",
  "painting.handcrafted.beach_sunrise_mid.title": "Beach Sunrise Mid",
  "painting.handcrafted.beach_sunrise_mid.author": "Handcrafted",
  "painting.handcrafted.apple.title": "Apple",
  "painting.handcrafted.apple.author": "Handcrafted",
  "painting.handcrafted.small_safari_sunset.title": "Small Safari Sunset",
  "painting.handcrafted.small_safari_sunset.author": "Handcrafted",
  "painting.handcrafted.marigold_meadows.title": "Marigold Meadows",
  "painting.handcrafted.marigold_meadows.author": "Handcrafted",
  "painting.handcrafted.ad_astra.title": "Ad Astra",
  "painting.handcrafted.ad_astra.author": "Handcrafted",
  "painting.handcrafted.love_flowers.title": "Love Flowers",
  "painting.handcrafted.love_flowers.author": "Handcrafted",
  "painting.handcrafted.misty_mountains.title": "Misty Mountains",
  "painting.handcrafted.misty_mountains.author": "Handcrafted",
  "painting.handcrafted.coral_depths.title": "Coral Depths",
  "painting.handcrafted.coral_depths.author": "Handcrafted",
  "painting.handcrafted.broken_birches.title": "Broken Birches",
  "painting.handcrafted.broken_birches.author": "Handcrafted",
  "painting.handcrafted.mysterious_mangroves.title": "Mysterious Mangroves",
  "painting.handcrafted.mysterious_mangroves.author": "Handcrafted",
  "painting.handcrafted.my_man_diorite.title": "My Man Diorite",
  "painting.handcrafted.my_man_diorite.author": "Handcrafted",
  "painting.handcrafted.cookies_on_a_plate.title": "Cookies on a Plate",
  "painting.handcrafted.cookies_on_a_plate.author": "Handcrafted",
  "painting.handcrafted.lava_puddles.title": "Lava Puddles",
  "painting.handcrafted.lava_puddles.author": "Handcrafted",
  "painting.handcrafted.the_cat_and_the_cup.title": "The Cat and the Cup",
  "painting.handcrafted.the_cat_and_the_cup.author": "Handcrafted",
  "painting.handcrafted.terrarium.title": "Terrarium",
  "painting.handcrafted.terrarium.author": "Handcrafted",
  "painting.handcrafted.green_woods.title": "Green Woods",
  "painting.handcrafted.green_woods.author": "Handcrafted",
  "painting.handcrafted.safari_sunset.title": "Safari Sunset",
  "painting.handcrafted.safari_sunset.author": "Handcrafted",
  "painting.handcrafted.rocky_beach.title": "Rocky Beach",
  "painting.handcrafted.rocky_beach.author": "Handcrafted",
  "painting.handcrafted.misty_mountain_left_sidepanel.title": "Misty Mountain Left Sidepanel",
  "painting.handcrafted.misty_mountain_left_sidepanel.author": "Handcrafted",
  "painting.handcrafted.misty_mountain_right_sidepanel.title": "Misty Mountain Right Sidepanel",
  "painting.handcrafted.misty_mountain_right_sidepanel.author": "Handcrafted",
  "painting.handcrafted.broken_birches_left_sidepanel.title": "Broken Birches Left Sidepanel",
  "painting.handcrafted.broken_birches_left_sidepanel.author": "Handcrafted",
  "painting.handcrafted.broken_birches_right_sidepanel.title": "Broken Birches Right Sidepanel",
  "painting.handcrafted.broken_birches_right_sidepanel.author": "Handcrafted",
  "painting.handcrafted.flower_in_the_darkness.title": "Flower in the Darkness",
  "painting.handcrafted.flower_in_the_darkness.author": "Handcrafted",
  "painting.handcrafted.desert_plateau.title": "Desert Plateau",
  "painting.handcrafted.desert_plateau.author": "Handcrafted",
  "painting.handcrafted.beach_sunrise_right.title": "Beach Sunrise Right",
  "painting.handcrafted.beach_sunrise_right.author": "Handcrafted",
  "painting.handcrafted.beach_sunrise_left.title": "Beach Sunrise Left",
  "painting.handcrafted.beach_sunrise_left.author": "Handcrafted",
  "painting.handcrafted.nian_cat.title": "Nian Cat",
  "painting.handcrafted.nian_cat.author": "Handcrafted"
}
```
</details>

**Comment by AlexNijjar** [comment]
Thank you, will be fixed in the next update.
