### ISSUE TITLE
[Bug]: Mobs can't see Handcrafted furniture

### ISSUE THREAD

**Issue by FumpleWumper** [terrarium-earth/Handcrafted#61]
### Bug Description

Mobs (mostly villagers in my case) just can't see Handcrafted items right in front of them and keep getting stuck on them while trying to move through them instead of just pathing around it, is there a way to fix this?

### Version

handcrafted-fabric-1.20.1-3.0.1

### Mod Loader Version

1.20.1 - 0.14.22

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Fixed in 563b0c1
