### ISSUE TITLE
[Bug]: Client crashes when attempting to render Chair(?)

### ISSUE THREAD

**Issue by Kurty00** [terrarium-earth/Handcrafted#62]
### Bug Description

The client randomly crashes while playing on a server. Both have the same version of Handcrafted.

### Expected Behavior

I'd expect the game not to crash.

### Version

2.0.6

### Mod Loader Version

1.19.2 - 0,14,22

### Mod Loader

Fabric

### Logs or additional context

https://share.k00.eu/latest.log
https://share.k00.eu/crash-2023-10-06_20.51.01-client.txt

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
can you try without sodium?

**Comment by AlexNijjar** [comment]
Also, 1.19.2 is no longer supported. If you're constantly experiencing this, let me know. But I have not seen this from anyone else.
