### ISSUE TITLE
[Bug]: a couple of very little visuals issues in the latest version

### ISSUE THREAD

**Issue by glittermutt** [terrarium-earth/Handcrafted#63]
### Bug Description

first off, i just wanna say, the new update is AMAZING, like, genuinely!!! its so good
i did find a couple of visual bugs though, theyre small but i figured itd still be good to report
1. the left side of tables, sidetables, desks and nightstands z-fights with sheets placed on top of them
2. the left right side of couches is always visually brighter than the rest
3. you cannot place sheets on dining benches
still, thank you so much for the hard work!

### How to Reproduce?

1. place a table, a sidetable, desk, nightstand and place a sheet on top
2. place down a connected couch (2 or more blocks)
3. place down a dining bench and try placing a sheet on top

### Expected Behavior

1. theres no z-fighting
2. the couch is evenly lit
3. (i assume) the dining bench is covered with a sheet

### Version

3.0.2

### Mod Loader Version

1.20.1 - latest

### Mod Loader

Quilt

### Logs or additional context

![2023-10-17_17 39 48](https://github.com/terrarium-earth/Handcrafted/assets/134949309/17dc2fc7-7e3f-4e9f-9f95-140ec0671f16)
![2023-10-17_17 39 55](https://github.com/terrarium-earth/Handcrafted/assets/134949309/6cf65bca-1a47-4d73-82d9-8618206a1665)
![2023-10-17_17 41 42](https://github.com/terrarium-earth/Handcrafted/assets/134949309/be15f065-2e98-476c-a7a7-105a7faa2aec)
![2023-10-17_17 50 03](https://github.com/terrarium-earth/Handcrafted/assets/134949309/b259182a-5b49-4713-9492-8457bcc2fa5d)

### Code of Conduct

- [x] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by glittermutt** [comment]
the log, if it's of any use
[latest.log](https://github.com/terrarium-earth/Handcrafted/files/12929061/latest.log)

**Comment by GJdude** [comment]
Can confirm I'm also seeing this with Fabric - in which case, I can also report performance is way up too, especially with the addition of Sodium, Lithium, etc. Great update!

Standard (iron) benches also have a similar issue to couches where the leftmost part is darker the the rest.

Counters also have some unusual lighting behavior when blocks and certain other things are placed around and above them. The surface shadow on top doesn't seem to come from the direction it should be and can end up darkening the entire block like so and breaking smooth lighting, even when there's a torch right on top:
![Untitled](https://github.com/terrarium-earth/Handcrafted/assets/83022658/ebd40dfa-cddb-4c58-8482-b60e0280d3c3)
Sodium 0.4.10 for 1.20.1 is running here, if that has any effect.

**Comment by AlexNijjar** [comment]
The z-fighting, couch & metal bench, and counter issue have been fixed. The dining bench currently does not have a sheet version, hence why placing a sheet on it doesn't do anything. I might add it in the future, though.
