### ISSUE TITLE
[Feature Request]: A way to remove/change sheets/pillows without breaking the block

### ISSUE THREAD

**Issue by vnsrz** [terrarium-earth/Handcrafted#67]
### Is your feature request related to a problem?

I'm trying different sheets to see which looks best, but for every sheet I have to break the table and place it again.

### Solution(s)

There should be a way of removing sheets/pillows without breaking the block they're on.

### Describe alternatives you've considered

Maybe shift-clicking on the block, or maybe using the hammer. And when clicking with another sheet/pillow, the old one should be replaced by the new one.

### Mod Version

3.0.3

### Mod Loader Version

0.14.22

### Mod Loader

Fabric

**Comment by AlexNijjar** [comment]
you can shift-right click with an empty hand. is that not working?

**Comment by vnsrz** [comment]
I had no idea, haha. It works only when my off-hand is also empty.
