### ISSUE TITLE
[Bug]: Crashes on Startup Fabric 1.19.3

### ISSUE THREAD

**Issue by Zykana** [terrarium-earth/Handcrafted#7]
### Bug Description

Crashes on startup.

### How to Reproduce?

Run the mod.

### Expected Behavior

Mod loads.

### Version

2.0.3

### Mod Loader Version

1.19.3

### Mod Loader

Fabric

### Logs or additional context

https://pastebin.com/DuKM7LNV

**Comment by DEVTomatoCake** [comment]
Can confirm

**Comment by antgly** [comment]
Same here.

**Comment by DEVTomatoCake** [comment]
Still not fixed for me, it now crashes with `java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'handcrafted'!`
Crash report: https://pastebin.com/9y9hNdWf

**Comment by AlexNijjar** [comment]
Whaaa, I just opened the game and it worked fine. Where are you downloading the jar from? Curse or modrinth?

**Comment by antgly** [comment]
Downloaded the latest version (2.0.3) from Modrinth including Resourceful Lib (latest) for 1.19.3.

**Comment by AlexNijjar** [comment]
Try downloading it from curse, I think the modrinth  version is broken

**Comment by antgly** [comment]
Happening with Curseforge as well.

**Comment by AlexNijjar** [comment]
Ah alright I’ll check it out in. Bit

**Comment by AlexNijjar** [comment]
alright I've replaced the system that was crashing so it will not happen anymore

**Comment by antgly** [comment]
Thank you so much for your contributions and timely response!

**Comment by SwampFalc** [comment]
So I just got bitten by this because on Modrinth, the broken 2.0.3 version is still "featured". You might want to unpublish that version...

**Comment by AlexNijjar** [comment]
oh, thanks. turned off manual featuring so it should auto-feature the latest now
