### ISSUE TITLE
[Bug]: Can walk through back of the couch

### ISSUE THREAD

**Issue by MrGreenTea** [terrarium-earth/Handcrafted#71]
### Bug Description

The couch has no collider for the backrest and so kind of acts like a slab in that I can just walk through it from behind.

### How to Reproduce?

1. Place a couch
2. Walk over it so you stand behind it
3. Turn 180 degrees and walk from behind over it
4. Stand before it again

### Expected Behavior

You should collide with the backrest same as with benches and chairs.

### Version

3.0.5

### Mod Loader Version

1.20.1 - 0.14.23

### Mod Loader

Fabric

### Logs or additional context

![2023-10-28_12 05 22](https://github.com/terrarium-earth/Handcrafted/assets/9407731/010a084c-b8fc-4fd1-80cf-aa527d7d29fc)

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by MrGreenTea** [comment]
I just noticed that you can also walk through the back of benches and chairs, it's just that the seating area is a bit higher than the step-height.

Is this intended?

**Comment by AlexNijjar** [comment]
Problem is that the furniture shapes are very complicated, especially the couches and benches as those have corner pieces. So it would require a ton of unique shapes for all the furniture.

**Comment by MrGreenTea** [comment]
> Problem is that the furniture shapes are very complicated, especially the couches and benches as those have corner pieces. So it would require a ton of unique shapes for all the furniture.

I understand, it is also not really that big of an issue. If you want close this issue, I won't mind :)
