### ISSUE TITLE
[Bug]: Recipe conflict: Comforts

### ISSUE THREAD

**Issue by kurtramone** [terrarium-earth/Handcrafted#73]
### Bug Description

Recipe from mod **Comforts** sleeping bag is the same as **White Sheet**

![Captura de tela 2023-11-07 140333](https://github.com/terrarium-earth/Handcrafted/assets/55619656/3cf49e56-e347-4f30-87c5-8a6683d5c661)
![Captura de tela 2023-11-07 140408](https://github.com/terrarium-earth/Handcrafted/assets/55619656/8a397cb6-05ec-43c2-9b94-30c7b696775a)

### How to Reproduce?

Look up recipes

### Expected Behavior

Being able to craft

### Version

2.0.6

### Mod Loader Version

1.19.2 - 43.3.2

### Mod Loader

Forge

### Logs or additional context

None

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Please do not create recipe conflict issues. It should be up to the modpack to fix it, not the modder.

**Comment by AlexNijjar** [comment]
you can also just use https://modrinth.com/mod/polymorph

**Comment by kurtramone** [comment]
@AlexNijjar I'm not a mod maker, not a modpacker maker, not a maker of any kind, I'm a guy who's using your mod

**Comment by AlexNijjar** [comment]
in that case, use polymorph
