### ISSUE TITLE
[Bug]: [1.19.2] Dining bench tanking FPS.

### ISSUE THREAD

**Issue by Sandriell** [terrarium-earth/Handcrafted#74]
### Bug Description

I have a structure built with a lot of dining benches and any time I am near that structure my FPS drops down to single digits.

Did a spark profile and most of the render pass seems to be spent on the dining bench.

https://spark.lucko.me/Y2eD6NU28n

Mod List: https://gist.github.com/Sandriell/585349d10e92a848fed149a6798773e3

### Expected Behavior

No render lag

### Version

handcrafted-forge-1.19.2-2.0.6

### Mod Loader Version

43.2.21

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
All performance issues were fixed in 1.20.1 and will likely not be backported.
