### ISSUE TITLE
[Bug]: Board creation not working

### ISSUE THREAD

**Issue by NanoPlaysGames** [terrarium-earth/Handcrafted#76]
### Bug Description

When throwing planks onto a stonecutter in most 1.20.1 versions, boards do not appear, making half of the furniture uncraftable.

### Expected Behavior

When throwing boards on a stonecutter, they disappear and are replaced by Boards of the same wood type.

### Version

3.0.5 - 3.0.1

### Mod Loader Version

1.20.1

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
they were removed. the recipes now use planks

**Comment by NanoPlaysGames** [comment]
Sorry for the trouble. I realised that later when I looked for boards in
JEI. Thank you for removing the report!
