### ISSUE TITLE
[Bug]: craft replacer

### ISSUE THREAD

**Issue by ArchetypeLegion** [terrarium-earth/Handcrafted#77]
### Bug Description

when you trying to craft a sheet with epic knight mod, it replace with wool fabric and you can't craft sheet.
![image](https://github.com/terrarium-earth/Handcrafted/assets/122025812/bfc7d4ef-ae24-4eea-b8e5-b2a0be8387c7)

### Version

3.0.5

### Mod Loader Version

1.20.1

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by Moongosu** [comment]
Try install Polymorph mod?

**Comment by AlexNijjar** [comment]
please don't make recipe conflict bug reports. just use polymorph.
