### ISSUE TITLE
[Feature Request]: Update for 1.19.0 pls

### ISSUE THREAD

**Issue by Plashot** [terrarium-earth/Handcrafted#8]
### Is your feature request related to a problem?

I want to add this mod to a friends server, but the server is in 1.19 :(

### Solution(s)

Update for 1.19

### Mod Version

2.0.0

### Mod Loader Version

1.19

**Comment by AlexNijjar** [comment]
we don't do back ports, but you should probably switch to 1.19.2 or 1.19.3 as that's the standard
