### ISSUE TITLE
[Bug]: Crashing when placing any storage block

### ISSUE THREAD

**Issue by igniter16** [terrarium-earth/Handcrafted#80]
### Bug Description

whenever i place a storage block (i.e drawers or shelfs etc) the game crashes 

### How to Reproduce?

place down any storage container added by the mod

### Expected Behavior

to be able to use storage containers without crashing

### Version

3.1.0

### Mod Loader Version

fabric-loader-0.15.1-1.20.4

### Mod Loader

Fabric

### Logs or additional context

[latest.log](https://github.com/terrarium-earth/Handcrafted/files/13705191/latest.log)

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
Handcrafted is only up to 1.20.2 not 1.20.4
