### ISSUE TITLE
[Bug]: Game crashes upon placing Desk/Table

### ISSUE THREAD

**Issue by Larlenn** [terrarium-earth/Handcrafted#82]
### Bug Description

Game completely crashes with Error when placing Desk/Table
Upon coming back, the Desk/Table that caused an error is gone
(all colours/wood types crash)

### How to Reproduce?

Place desk/table

### Expected Behavior

Game not to crash

### Version

1.20.4

### Mod Loader Version

0.15.3-1.20.4

### Mod Loader

Fabric

### Logs or additional context

https://pastebin.com/B2SNMtCE

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
1.20.4 isn’t supported yet.
