### ISSUE TITLE
[Bug]: Intense frame drops.

### ISSUE THREAD

**Issue by Vadeline666** [terrarium-earth/Handcrafted#83]
### Bug Description

Whenever I look at any handcrafted furniture, it significantly drops the frame rate. I usually run MC at a comfortable 60-50 FPS but whenever I have the items in my inventory or look them up in the JEI system I drop down to 14-20ish with or without a shader pack on.

(NOTE: I do not have optifine since it causes crashes and I'm using Oculus/Iris instead)

### Version

2.0.6

### Mod Loader Version

1.19.2

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Handcrafted was rewritten in 1.20.1 to fix all performance related issues. I currently do not plan on backporting to 1.19.2.
