### ISSUE TITLE
[Bug]: Unable to use night stand

### ISSUE THREAD

**Issue by NorthZeroD** [terrarium-earth/Handcrafted#85]
### Bug Description

(The following content is machine translated.)

I can't use night stands. I have tried right clicking countless times, but the night stands cannot be opened at all.
If it's just an unusable decoration, why use a chest to make it?
This is a great mod, I played it in Better MC. I hope the author can fix this bug.

Minecraft version: 1.19.2
Mod Loader: fabric
Handcrafted version: handcrafted-fabric-1.19.2-2.0.6
Resourcefullib version: resourcefullib-fabric-1.19.2-1.1.24

https://github.com/terrarium-earth/Handcrafted/assets/141613738/2ea01814-10c6-4466-8c26-9bdd361929d9

<img width="306" alt="屏幕截图 2024-02-02 120220" src="https://github.com/terrarium-earth/Handcrafted/assets/141613738/59afe090-77d8-48b1-9a52-ab955b5bdf85">

### How to Reproduce?

1.  Place a night stand.
2.  Right click on it.
3.  Cannot be opened.

### Expected Behavior

Right click to open the night stands.

### Version

2.0.6

### Mod Loader Version

0.77.0

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
It's been fixed in 1.20.1. It just wont be backported
