### ISSUE TITLE
[Bug]: Furniture Loses Color/Direction When Updating

### ISSUE THREAD

**Issue by Schoperation** [terrarium-earth/Handcrafted#86]
### Bug Description

Hello, I recently updated my pack from 1.19.2 to 1.20.1, and I'm seeing some weird things with my furniture. 

For example, with the couch below, it should be red and facing the other way.

And with the chairs, they should be facing towards the table. I noticed this affected my fancy bed as well; it should be dark blue but it's white now (no change in direction, though).

![2024-02-07_22 19 16](https://github.com/terrarium-earth/Handcrafted/assets/18017369/ebd32d04-14e7-4e40-9093-54c356832db9)

![2024-02-07_22 25 39](https://github.com/terrarium-earth/Handcrafted/assets/18017369/7c1944da-528c-4ddf-be01-f8e710d00744)

### How to Reproduce?

1. Place down a handcrafted couch in 1.19.2
2. Color it something
3. Log out
4. Update mod to 1.20.1
5. Log back in
6. Couch is no longer said color

### Expected Behavior

Couch should be facing the same way, and same color as I made it so in 1.19.2; ditto for other furniture.

### Version

3.0.5

### Mod Loader Version

1.20.1 - 47.2.20

### Mod Loader

Forge

### Logs or additional context

[latest.log](https://github.com/terrarium-earth/Handcrafted/files/14203925/latest.log)
[debug.log](https://github.com/terrarium-earth/Handcrafted/files/14203926/debug.log)

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
the mod was rewritten in 1.20.1 so a lot of the blocks need to be broken and placed again. I can’t really do anything about it

**Comment by Schoperation** [comment]
Alright makes sense, thanks for responding.
