### ISSUE TITLE
[Bug]: Can't add sheets to dining benches

### ISSUE THREAD

**Issue by Eario** [terrarium-earth/Handcrafted#87]
### Bug Description

When attempting to place a sheet on a dining bench, you instead sit on it. Holding shift results in neither sitting nor placement of the sheet on the bench.

### How to Reproduce?

1. Place any Dining Bench block.
2. Hold any Sheet item.
3. Right-click on the Dining Bench block.

### Expected Behavior

The sheet should be placed on the bench, rather than the player sitting down.

### Version

3.0.5

### Mod Loader Version

1.20.1 - 47.1.99

### Mod Loader

NeoForge

### Logs or additional context

While this isn't the absolute latest version of the mod, it is the last version on this particular game version, which many other mods have not updated past. It would be appreciated if a fix for this was applied.

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
They're actually not meant to have sheets, the tooltip isn't meant to say that. I fixed it in 1.20.4 and will backport it when I have a chance.
