### ISSUE TITLE
[Bug]: fancybed doesnt have a texture

### ISSUE THREAD

**Issue by Cris06cool** [terrarium-earth/Handcrafted#88]
### Bug Description

The Fancy Bed is just a full birch block with some part of the model sticking out

### How to Reproduce?

1. Craft the bed 2. Place it down

### Expected Behavior

i expected to have a normal looking bed

### Version

2.0.6

### Mod Loader Version

1.19.2 Forge 43.3.0

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
this is fixed in 1.20.1 and won’t be backported. it’s an issue with some block entity and bed optimization mods. remove those if you have it.

**Comment by Cris06cool** [comment]
dum., 18 feb. 2024, 19:02 Alex ***@***.***> a scris:
