### ISSUE TITLE
[Bug]: Boards not working

### ISSUE THREAD

**Issue by Stuopid** [terrarium-earth/Handcrafted#89]
### Bug Description

I was playing on my modpack when I realized if i threw planks on a stonecutter it did **not** gave me boards. It used to give it but I dont rlly know why. Probably some mods are **conflicting** with handcrafted. **I** **dont** **know** which one is it tho.

### How to Reproduce?

 https://paste.atlauncher.com/view/92528286-da8a-4af6-9bec-bbe578e588c3

### Expected Behavior

Expected to get **boards** when I threw **planks** at the **stonecutter**

### Version

2.0.6, latest one I think

### Mod Loader Version

1.19.2 43.3.5

### Mod Loader

Forge

### Logs or additional context

 https://paste.atlauncher.com/view/92528286-da8a-4af6-9bec-bbe578e588c3

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
remove spelunkery or update to 1.20.1
