### ISSUE TITLE
[Bug]: handcrafted hammer overrites/deletse ad_astra hammer and cant find/build (even with polymorph??)

### ISSUE THREAD

**Issue by hiimrickross** [terrarium-earth/Handcrafted#93]
### Bug Description

as per title, im playing prominence classic and when i was looking at the ad astra questbook i saw the starter quest to make the hammer was broken. EMI couldn't find it either. Later at another time I tried to make the recipe manually and it resulted in the handcrafted hammer without being able to change it on Polymorph either.

the weird thing is that in the latest (or second latest) ver of Prominence Classic II Forge (2.5.5), it comes with Handcrafted and it works fine as the handcrafted hammer requests handcrafted boards rather than sticks. I tried to open the jar and find the hammer recipe to change it in my older Prominence version, but failed to find it. I'm unsure why Polymorph is not working for it / the ad astra hammer is being deleted by the handcrafted one(?).

the changelogs on version 2.0.0hf to version 2.6.0 for prom classic don't mention handcrafted at all so I'm stumped on options here and so must consult you since maybe it's a simple fix. There are many mods that polymorph let me change the recipes of freely, I've never ran into this before.

### How to Reproduce?

have both mods, try to make hammer.

### Expected Behavior

polymorph be able to swap between either, plus also ad astra hammer being spawnable or findable in emi at least not deleted.

### Version

3.0.6

### Mod Loader Version

1.20.1

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
The hammer doesn't exist in Ad Astra anymore. Your are now meant to craft plates by putting them in an ad astra compressor.

**Comment by hiimrickross** [comment]
> Member

ah that would explain it then. I downloaded a fresh version of prominence 2.6.0 / latest and saw that it's using a very old version of ad astra (1.15.5 vs the 1.15.18 that I have on my own self-updated version of an older prominence pack. Is the handcrafted hammer recipe intended to be 2 sticks 2 iron ingots? That's what I'm seeing on ver 3.0.6 of handcrafted when 'just adding the mod' to the modpack i'm playing. Just want to make sure it's all correct now that you have explained the Ad Astra changes.

The aforementioned prominence pack (2.6.0) uses a slightly diff recipe of 2 iron ingots and 2 #handcrafted:boards

**Comment by AlexNijjar** [comment]
yes. the handcrafted hammer recipe is 2 sticks and 2 iron ingots
